### PR TITLE
improve dynamic shares test

### PR DESCRIPTION
**Pull request by glommer**
This was sitting on my branch and I forgot to merge it when I merged
the dynamic tests share =(

The way the code is right now is a bit fragile and it will fail once
we change some scheduler parameters. This change makes it more robust.

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture
[] The new code I am adding is formatted using `rustfmt`

### CODE REVIEW

**Comment by matklad** [comment]
Hm, `executor::test::test_dynamic_shares` consistently passes on my machine before  this commit and consistently fails afterwards.

**Comment by glommer** [comment]
thanks for the report. I was afraid of that =( This test is quite sensitive to local condition, although I tried to run it under various different scenarios. I may unfortunately just yank it =(

But before we give up on that entirely, could you please print the values of `tq1_count`, `tq2_count` and `ratios` at the end of the test ?

**Comment by matklad** [comment]
Here are a couple of runs:


```
failures:

---- executor::test::test_dynamic_shares stdout ----
[scipio/src/executor.rs:1565] tq1_count = RefCell {
    value: [
        222643,
        229892,
    ],
}
[scipio/src/executor.rs:1565] tq2_count = RefCell {
    value: [
        202,
        204,
    ],
}
[scipio/src/executor.rs:1565] &ratios = [
    0.0009072820614167075,
    0.0008873732013293199,
]
thread 'executor::test::test_dynamic_shares' panicked at 'assertion failed: ratios[1] > ratios[0]', scipio/src/executor.rs:1566:13

failures:

---- executor::test::test_dynamic_shares stdout ----
[scipio/src/executor.rs:1565] tq1_count = RefCell {
    value: [
        209386,
        209685,
    ],
}
[scipio/src/executor.rs:1565] tq2_count = RefCell {
    value: [
        180,
        225,
    ],
}
[scipio/src/executor.rs:1565] &ratios = [
    0.0008596563285033383,
    0.0010730381286215038,
]

failures:

---- executor::test::test_dynamic_shares stdout ----
[scipio/src/executor.rs:1565] tq1_count = RefCell {
    value: [
        222643,
        229892,
    ],
}
[scipio/src/executor.rs:1565] tq2_count = RefCell {
    value: [
        202,
        204,
    ],
}
[scipio/src/executor.rs:1565] &ratios = [
    0.0009072820614167075,
    0.0008873732013293199,
]
thread 'executor::test::test_dynamic_shares' panicked at 'assertion failed: ratios[1] > ratios[0]', scipio/src/executor.rs:1566:13
```

**Comment by glommer** [comment]
Ok, I think I know what is going on.
Does it pass if you merge https://github.com/DataDog/scipio/pull/108 ?

I probably had that locally in all runs that passed. The results you post are really surprising and indicate that the scheduler is not reverting back to the second task *at all* - which is one of the bugs I fixed in that series.

**Pull request merged**
